<?xml version="1.0"?> <!-- specifies the XML version being used (1.0) -->
<robot name="my_robot" xmlns:xacro="http://ww.ros.org/wiki/xacro">
    <xacro:property name="laser_radius" value="0.05" />
    <xacro:property name="laser_length" value="0.04" />
    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${laser_radius}" l="${laser_length}"
                                    o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>
    <joint name="base_laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_link"/>
        <origin xyz="-${base_length / 3.0} 0 ${base_height + (laser_length / 2.0)}" rpy="0 0 ${pi}"/>
    </joint>
    <gazebo reference="laser_link">
        <sensor name="laser_sensor" type="gpu_lidar">
            <pose>0 0 0 0 0 0</pose>
            <topic>scan</topic>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle>
                        <max_angle>3.14159</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
        </sensor>
    </gazebo>
      
</robot>
